{
    'name': 'Food Search Application',
    'version': '16.0',
    'summary': """Custom Module""",
    'description': """Kapil""",
    'category': 'Food',
    'author': 'Kapil',
    'company': 'Kapil Test',
    'maintainer': 'Kapil',
    'depends': ['base','crm'],
    'website': 'https://www.cybrosys.com',
    'data': [
        'security/ir.model.access.csv',
        'views/product_details_view.xml',
        'views/my_dashboard.xml',
        'views/product_details_view.xml',
        'views/all_product_details_controller.xml',
        'views/product_toppings.xml',
        'views/ratings.xml',
        'views/toppings.xml',
        'views/toppings_groups.xml',
    ],
    'license': 'LGPL-3',
    'sequence':-100,
    'installable': True,
    'auto_install': False,
    'application': True,
}
